## link https://doc.rust-lang.org/cargo/reference/config.html 

# default runner starts a GDB sesssion, which requires OpenOCD to be
# running, e.g.,
## openocd -f interface/stlink.cfg -f target/stm32f3x.cfg
# depending on your local GDB, pick one of the following

[target.thumbv7em-none-eabihf]
#runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"
runner = "gdb-multiarch -q -x openocd.gdb"
# runner = "gdb -q -x ../openocd.gdb"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"
# this specifies the cross compilation (seems a bit weird to not have this in the Cargo.toml file where the rest of the details are specified)
